# Create a 3x3x3 array with random values

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.45413252 0.79013283 0.54492051]
  [0.81491544 0.7732642  0.54984884]
  [0.45378073 0.53188678 0.08456485]]

 [[0.56877543 0.49017502 0.16823753]
  [0.28902934 0.88778307 0.83409058]
  [0.64395173 0.71275808 0.74351657]]

 [[0.70381967 0.30518202 0.60129911]
  [0.39232897 0.11324953 0.02349135]
  [0.24429706 0.87632254 0.914311  ]]]


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5), dtype=int)

# Set values 1, 2, 3, and 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
# Create an 8x8 matrix filled with zeros
matrix= np.zeros((8,8), dtype = int)
# Fill the checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [9]:
# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(matrix)
std = np.std(matrix)

# Normalize the matrix
normalized_matrix = (matrix - mean) / std

print("Original Matrix: ")
print(matrix)
print("\nNormalized Matrix: ")
print(normalized_matrix)


Original Matrix: 
[[0.88578597 0.20549411 0.49385462 0.82370681 0.64300617]
 [0.02331642 0.12224587 0.82267938 0.03497783 0.87028971]
 [0.0393729  0.81194269 0.7499179  0.36847891 0.23754086]
 [0.00711529 0.65519009 0.37149766 0.80545699 0.23699052]
 [0.79460463 0.89524405 0.14256385 0.030724   0.02193523]]

Normalized Matrix: 
[[ 1.31313535 -0.70780886  0.14882419  1.12871667  0.59190897]
 [-1.24900446 -0.95511457  1.12566447 -1.21436189  1.26710058]
 [-1.20130543  1.09376899  0.90951184 -0.22362963 -0.61260753]
 [-1.29713319  0.62810377 -0.21466184  1.07450191 -0.61424242]
 [ 1.04226279  1.34123248 -0.89475592 -1.22699873 -1.25310756]]


# How to find common values between  two arrays

In [11]:
# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 9])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)


[4 5]


# How to get the dates of yesterday today and tomorrow

In [13]:
import datetime

# Get today's date
today = datetime.date.today()

# Calculate yesterday and tomorrow
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-19
Today: 2023-09-21
Tomorrow: 2023-09-23


# Consider 2 random array A and B, check they are equal

In [14]:
# Generate two random arrays A and B
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if the arrays are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


In [15]:
A

array([[0.88555865, 0.03896129, 0.50613329],
       [0.66253385, 0.96405417, 0.51915114],
       [0.71846808, 0.91286661, 0.59976592]])

In [16]:
B

array([[0.8118037 , 0.88607481, 0.72043288],
       [0.15373337, 0.5610427 , 0.23057736],
       [0.0393165 , 0.14827302, 0.59425107]])

# Create random vector of size 10 and replace the maximum value by 0

In [29]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced:")
print(random_vector)


Random vector with the maximum value replaced:
[0.6983556  0.39122225 0.63942603 0.7177719  0.55212086 0.
 0.49059016 0.71074956 0.19427852 0.10816407]


# How to print all the values of an array using numpy 

In [22]:
arr =np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


# Subtract the mean of each row of a matrix

In [23]:
import numpy as np

# Create a sample matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix
result_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# Consider a vector, how to add 1 to each element indexed by a second vector(be careful with repeated indices)

In [24]:
import numpy as np

# Create a vector (replace this with your vector)
vector = np.array([10, 20, 30, 40, 50])

# Create a second vector with indices (replace this with your indices)
indices = np.array([1, 3, 1, 4, 2])

# Create a mask to mark unique indices
unique_indices = np.unique(indices)

# Add 1 to elements at unique indices
vector[unique_indices] += 1

print("Original Vector:")
print(vector)


Original Vector:
[10 21 31 41 51]


# How to get the diagonal of a dot product

In [25]:
# Create two matrices 
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Calculate the dot product
dot_product = np.dot(matrix1, matrix2)

# Extract the diagonal elements
diagonal = np.diag(dot_product)

print("Dot Product Matrix:")
print(dot_product)
print("\nDiagonal Elements of Dot Product:")
print(diagonal)


Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements of Dot Product:
[30 69 90]


# How to find the most frequent value in an array using numpy

In [27]:
# Create a NumPy array (replace this with your array)
my_array = np.array([10, 20, 20, 30, 30, 30, 40, 40, 40, 44])

# Find the most frequent value
most_frequent_value = np.bincount(my_array).argmax()

print("Most Frequent Value:", most_frequent_value)


Most Frequent Value: 30


# How to get the n largest values of an array

In [31]:
# Create a NumPy array 
arr = np.array([1,2,3,4,5,6,7,8,9])

# Set the value of n for the n largest values
n = 3

# Use numpy.partition to get the n largest values
n_largest_values = np.partition(arr, -n)[-n:]

print(f"The {n} largest values are: {n_largest_values}")


The 3 largest values are: [7 8 9]


# How to create a record array from a regular array

In [32]:
# Create a regular NumPy array
regular_array = np.array([(1, 'Kohli', 25),
                           (2, 'Rohit', 30),
                           (3, 'Gill', 22)],
                          dtype=[('ID', int), ('Name', ''), ('Age', int)])

# Create a record array from the regular array
record_array = regular_array.view(np.recarray)

# Access elements in the record array by field names
print("Record Array:")
print(record_array)
print("\nAccessing elements by field name:")
print("ID:", record_array.ID)
print("Name:", record_array.Name)
print("Age:", record_array.Age)


Record Array:
[(1, 'Kohli', 25) (2, 'Rohit', 30) (3, 'Gill', 22)]

Accessing elements by field name:
ID: [1 2 3]
Name: ['Kohli' 'Rohit' 'Gill']
Age: [25 30 22]


# How to swap two rows of an array

In [34]:
# Create a sample 2D NumPy array 
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Specify the indices of the rows you want to swap
row1_index = 0  # Index of the first row
row2_index = 2  # Index of the second row

# Swap the rows
array[[row1_index, row2_index]] = array[[row2_index, row1_index]]

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Write python code to reshape to the next dimension of numpy array

In [33]:
# Create a 1D NumPy array 
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to the next dimension (2D array)
next_dimension_array = original_array.reshape(-1, 1)

print("Original Array (1D):")
print(original_array)
print("\nReshaped Array (2D - Next Dimension):")
print(next_dimension_array)


Original Array (1D):
[1 2 3 4 5 6]

Reshaped Array (2D - Next Dimension):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
